### PR TITLE
chore: sanitize entity and transform response

### PR DESCRIPTION
**Pull request by ChristopheCVB**
### Description

Sanitize and Transform Entities when emiting

### Type of change

- [ ] Documentation (updates to the documentation or readme)
- [ ] Bug fix (a non-breaking change that fixes an issue)
- [ ] Enhancement (improving an existing functionality like performance)
- [ ] New feature (a non-breaking change that adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by ChristopheCVB** [comment]
Let me know what you think. I would still need to update the documentation if you're willing to merge this

**Comment by ChristopheCVB** [comment]
@derrickmehaffy I would be also interested in having your opinion ;)

**Comment by ComfortablyCoding** [comment]
Thanks for the report. It looks like this is an issue for admin emits only, although I do not see this implementation fix the issue.

The data gets transformed to a somewhat correct format but it does not remove the original top level results key. 
```json
{
  "data": {
    "attributes": {
      "results": [
        {
          "id": 3,
          "title": "My Article",
          "private": null,
          "createdAt": "2022-10-09T18:26:23.996Z",
          "updatedAt": "2023-02-26T15:58:31.556Z",
          "publishedAt": "2023-02-26T15:58:31.555Z",
          "messages": { "count": 1 },
          "createdBy": null,
          "updatedBy": {
            "id": 1,
            "firstname": "kai",
            "lastname": "doe",
            "username": null
          }
        }
      ],
      "pagination": { "page": 1, "pageSize": 10, "pageCount": 1, "total": 3 }
    }
  },
  "meta": {}
}
```

Additionally the data does not get sanitzed properly (e.g. message in the exampe above should not be there) which I assume is due to the current role (room) being emitted to being passed to it.

At the moment I am thinking maybe to add additional emits to the top level one specifying if it originated from the admin or the api.

**Comment by ChristopheCVB** [comment]
Yeah, that `results` comes from the `strapi.db.query` directly it seems. Anyway, I opened a discussion about refactoring this plugin to use entityService decorator
https://github.com/ComfortablyCoding/strapi-plugin-io/discussions/52

**Comment by ComfortablyCoding** [comment]
I left a comment in #52

**Comment by ComfortablyCoding** [comment]
This should be available in v2, feel free to check it out early using the v2.0.0 branch. 

NOTE: As its a major version their are breaking changes.

**Comment by ComfortablyCoding** [comment]
Closing as this has been resolved with the release of v2

**Pull request closed without merging**
